<?php
session_start();
$apikey="rzp_test_y7KqmfqPSudgnN";
$amount = $_SESSION["variable"];
?>

<form action="" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apikey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $amount*100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR" // You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="1"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="The Book Look"
    data-description="A book store at home"
    data-image="https://traindev.com/img/web-design-development.png"
    data-prefill.name="<?php echo $_POST['name'];?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-prefill.mobile="<?php echo $_POST['mobile'];?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>
